language: smalltalk
sudo: false

os:
  - linux

env:
  - GSCI_CLIENTS="Pharo-6.0"
  - GSCI_CLIENTS="Pharo-6.1"
  - GSCI_CLIENTS="Pharo-5.0"
  - GSCI_CLIENTS="Pharo-4.0 Pharo-3.0"

smalltalk:
  - GemStone-3.2.17
  - GemStone-3.3.9
  - GemStone-3.4.5
  - GemStone-3.5.1

matrix:
   allow_failures:
     - smalltalk: GemStone-3.4.3
       env: GSCI_CLIENTS="Pharo-4.0 Pharo-3.0"
     - smalltalk: GemStone-3.3.9
       env: GSCI_CLIENTS="Pharo-4.0 Pharo-3.0"
     - smalltalk: GemStone-3.2.17

notifications:
  slack: gemtalksystems:4YWbzy6sJN9cE0FhxvUPP8nS
  
cache:
  directories:
    - $SMALLTALK_CI_CACHE

