language: smalltalk
sudo: false

os:
  - linux

env:
#  - GSCI_CLIENT=Pharo-4.0
  - GSCI_CLIENT=Pharo-5.0
#  - GSCI_CLIENT=Pharo-3.0

smalltalk:
  - GemStone-3.2.12
  - GemStone-3.3.0

matrix:
   allow_failures:
     - smalltalk: GemStone-3.2.12

cache:
  directories:
    - $SMALLTALK_CI_CACHE
