language: smalltalk
sudo: false

os:
  - linux

env:
  - GSCI_CLIENTS="Pharo-5.0"
  - GSCI_CLIENTS="Pharo-4.0 Pharo-3.0"

smalltalk:
  - GemStone-3.2.17
  - GemStone-3.3.5

matrix:
   allow_failures:
     - smalltalk: GemStone-3.3.5
       env: GSCI_CLIENTS="Pharo-4.0 Pharo-3.0"
     - smalltalk: GemStone-3.2.17

cache:
  directories:
    - $SMALLTALK_CI_CACHE

